version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: mavilledb-container
    environment:
      POSTGRES_USER: USER
      POSTGRES_PASSWORD: user
      POSTGRES_DB: mavilledb
    ports:
      - "5432:5432"
    volumes:
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./src/main/resources/data.sql:/docker-entrypoint-initdb.d/02-data.sql
    networks:
      - app-network

networks:
  app-network: